# QOAN Documentation config file

# Allows use of Request Handler's default internal action manager.
allow_default_get_action: 1

component_load_order:
  - request

http_debug:
  allow        : 1
  allow_public : 1

